[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200


[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]
  
  checkPaths = [
    '/public/index.html',
    '/src/components/About.tsx',
    '/src/components/Gallery.tsx',
    '/src/components/Project.tsx',
  ]
  