[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/projects"
  to = "/projects"
  status = 301
  force = false
  query = {path = ":path"}


# [[plugins]]
# package = "netlify-plugin-a11y"
# [plugins.inputs]
  
# checkPaths = ['/index.html']
  